### ISSUE TITLE
前端技术学习的方式

### ISSUE THREAD

**Issue by Asunny-ren** [geekplux/ama#2]
我看见你学习到的前端技术还是挺丰富的，虽然我也了解一些，但是感觉学习起新的技术或者框架没有窍门和动力，总感觉力不从心，我想问一下你学习前端技术的方法，如何在工作之余去学习一些新的技术。

**Comment by geekplux** [comment]
看了你的几个 Project，感觉CSS水平不错啊。

我觉得兴趣和好奇心还是第一位吧，如果没有兴趣那真的是比较难熬。
我的建议是先找到能让你有兴趣的点，比如哪个技术能赚钱（赚钱一般人都有兴趣），能做好玩的东西等等。然后学习方法就是找关键词->搜索->买书->实践，我有篇博客你也可以参考下 [建立索引式的学习方法](http://geekplux.com/2015/12/08/learning-by-index.html)。

其实学什么都是这样的，这类问题，一般最后的结局都是「道理我都懂」系列。所以最关键的还是找到你的内在动力吧，我知道在山西的环境可能比较没什么追求，但是地域不是局限，在网上世界触手可及。多接触你从没接触过、想接触但一直没敢的东西。比如能上github经常提 PR就不错。

加油，共勉。
