### ISSUE TITLE
来自初学者的仰慕

### ISSUE THREAD

**Issue by hmjmifan** [geekplux/ama#8]
您好，我是在网上查阅资料的时候看到了您的博客，然后学习了一下午，感觉囫囵吞枣的了解了一下。在这之前我已经在一家创业型公司实习了一段时间，所做的数据可视化。说是数据可视化，就是用第三方软件，帆软进行一些图表的拖拽。看了您的文章我才算是打开了可视化的大门。想跟您咨询一下，如果往这方面发展的话，我应该掌握哪些技能，哪些书籍需要熟读。这样问可能有些唐突，谢谢您。

**Comment by geekplux** [comment]
谢谢，诚惶诚恐。数据可视化没有那么神秘，我那几篇文章其实说的都是基础。你可以买浙大陈为老师的《数据可视化》一书入门，也可以去学习一下 [cse442](https://courses.cs.washington.edu/courses/cse442/18au/) 或 [cse512](https://courses.cs.washington.edu/courses/cse512/18sp/)
