### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by LukerSpringtree** [geekplux/ama#9]
看了你很多篇博客,崇拜你的能力,羡慕你的经历.
最后看到了这个环节,多向你学习.

`http://d2forum.alibaba-inc.com/13#/index?_k=c7f2b9`

请问这个网站的 上面的 三潭印月那个动效是怎么实现. 有可以学习的资料吗? 有demo代码吗? 谢了!
麻烦.

**Comment by geekplux** [comment]
https://matthew.wagerfield.com/parallax/
用了这个
